<div class="title">
	<p>Add Country</p>
</div>
<form name="add" action="" method="post">
<table>	
	<tr>
		<td>Country Name:</td>
		<td><input type="text" name="data[country_name]" value=""></td>
	</tr>
	<tr>
		<td>Country Code:</td>
		<td><input type="text" name="data[country_code]" value=""></td>
	</tr>
	<tr>
		<td colspan="2"> <input type="submit" value="Add" name="data[submit]"> </td>
	</tr>
</table> 