<!DOCTYPE html>
<html lang="en">
    <head><meta charset="utf-8"></head>
    <body>
        <div class="header">
            <div class="navbar-inner">
                <div class="container">                    
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li class="active"><a href=""><?php echo 'Test Link'; ?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php //echo $this->content; ?>            
            <footer>
                <p>&copy; Online-Exam All Rights Reserved</p>
            </footer>
        </div>
    </body>
</html>
