<?php 
$this->registerJs('my.js');
$this->registerCss('test.css');  

?>

<div class="content">
	<p class="title">Welcome to EasyGo Framework</p>
	<div class="description">
		Welcome to the easygo framework. It is easy to develop and maintain applications with EasyGo framework.
		The easygo framework highly focus on best MVC practices and take care of low level implementation so that you can write
		actual code required for you application. The EasyGo framework is well structured and follow the best practices of 
		OOPS. 
		
		Features
		<ul>
			<li>It does follow MVC.</li>
			<li>It is object oriented.</li>
			
			<li>It does provide Themes, you can develop more than one theme for your application and can change theme on the fly.</li>
			<li>It does provide Plugins that's allows you to modify existing functionality or add new features in to your application.</li>
			<li>It does uses Event Driven architecture.</li>
			<li>It does uses in built Hooks and also allows developer to create new hooks.</li>
			<li>It is easy to develop SAAS based applications with EasyGo.</li>
		</ul>
		
	</div>
</div>